[project]
name = "ComfyUI-JakeUpgrade"
description = "ComfyUI workflow customization by Jake."
version = "1.0.0"
license = "LICENSE"
dependencies = ["opencv-python", "piexif", "simpleeval"]

[project.urls]
Repository = "https://github.com/pythongosssss/ComfyUI-WD14-Tagger"

[tool.comfy]
PublisherId = "jakechai"
DisplayName = "ComfyUI-JakeUpgrade"
Icon = ""
